"""Tests for :mod:`bioscout.utils.session_form` — the session editor's model.

The thing being pinned is that editing a field changes THAT field and nothing
else. session.yaml is hand-written and its comments carry the study's reasoning;
a save that quietly reflows the file or drops a comment block is unrecoverable
and looks like success.

Needs PyYAML (so does bioscout), nothing else.
"""
from __future__ import annotations

import shutil
import tempfile
import unittest
from pathlib import Path

from bioscout.utils.session_form import SessionForm

# A session.yaml with the shapes that matter: a leading comment block, a
# trailing comment on a value, a block list, a flow-ish nested mapping, and the
# trials/iterations structure.
SESSION_YAML = """\
# Generated by split_sessions.py — the pre/sprints/post split.
# ONE CEINMS CALIBRATION PER FATIGUE STATE — that is the point of the
# split. Losing this comment loses the reason the study is designed this way.
subject: 18
session: pre
body_mass: 89.4          # weighed from the static trial
static_trial: static1
markerset: setup_files/markers_FAIS.xml
setup_folder: setup_files
calibration_trials:
- Run_baselineA1
- Run_baselineA2
normalisation_trials:
- HAB1
- HAB2
emg_map:
  Voltage_1-VM:
  - vasmed_l
  Voltage_2-VL:
  - vaslat_l
ceinms:
  alpha: 10
  beta: 1
  gamma: 1000
trials:
  HAB1:
    type: generic
  HAB2:
    type: generic
  Run_baselineA1:
    type: running
  Run_baselineA2:
    type: running
  static1:
    type: static
iterations:
  rajagopal_fai:
    generic: Rajagopal2015_FAI_os4.osim
    so_model: 022_Rajagopal2015_FAI.osim
    prescaled: true
    label: Rajagopal FAI 022
"""


class _Session(unittest.TestCase):
    def setUp(self):
        self.tmp = Path(tempfile.mkdtemp(prefix="bioscout_session_form_"))
        self.addCleanup(shutil.rmtree, self.tmp, True)
        self.sess = self.tmp / "022" / "pre"
        (self.sess / "1_c3dfiles").mkdir(parents=True)
        for name in ("HAB1", "HAB2", "Run_baselineA1", "Run_baselineA2", "static1"):
            (self.sess / "1_c3dfiles" / f"{name}.c3d").write_bytes(b"c3d")
        self.yaml_path = self.sess / "session.yaml"
        self.yaml_path.write_text(SESSION_YAML, encoding="utf-8")

    def form(self):
        return SessionForm(self.sess)


class TestReading(_Session):
    def test_detects_an_existing_session(self):
        f = self.form()
        self.assertTrue(f.exists)
        self.assertEqual(f.value("subject"), 18)
        self.assertEqual(f.value("static_trial"), "static1")
        self.assertEqual(f.value("body_mass"), 89.4)

    def test_missing_session_is_not_an_error(self):
        empty = self.tmp / "023" / "pre"
        (empty / "1_c3dfiles").mkdir(parents=True)
        f = SessionForm(empty)
        self.assertFalse(f.exists)
        self.assertEqual(f.trials(), [])

    def test_trials_come_from_yaml_then_extra_c3d(self):
        (self.sess / "1_c3dfiles" / "SJ1.c3d").write_bytes(b"c3d")
        trials = self.form().trials()
        self.assertEqual(trials[0], "HAB1")          # yaml order preserved
        self.assertIn("SJ1", trials)                 # c3d with no yaml entry
        self.assertEqual(trials[-1], "SJ1")          # extras appended

    def test_trial_types(self):
        types = self.form().trial_types()
        self.assertEqual(types["static1"], "static")
        self.assertEqual(types["Run_baselineA1"], "running")


class TestRedFlags(_Session):
    def test_clean_session_has_none(self):
        self.assertEqual(self.form().problems(), [])

    def test_empty_c3d_folder_is_the_loudest_flag(self):
        for p in (self.sess / "1_c3dfiles").glob("*.c3d"):
            p.unlink()
        problems = self.form().problems()
        self.assertTrue(problems)
        self.assertIn("NO C3D FILES", problems[0])

    def test_static_trial_not_in_session(self):
        self.yaml_path.write_text(
            SESSION_YAML.replace("static_trial: static1", "static_trial: static9"),
            encoding="utf-8")
        self.assertTrue(any("static9" in p for p in self.form().problems()))

    def test_missing_static_trial_key(self):
        self.yaml_path.write_text(
            SESSION_YAML.replace("static_trial: static1\n", ""), encoding="utf-8")
        self.assertTrue(any("no static_trial" in p for p in self.form().problems()))

    def test_calibration_trial_that_does_not_exist(self):
        self.yaml_path.write_text(
            SESSION_YAML.replace("- Run_baselineA2", "- Run_ghost"), encoding="utf-8")
        self.assertTrue(any("Run_ghost" in p and "calibration_trials" in p
                            for p in self.form().problems()))

    def test_c3d_without_a_trial_entry(self):
        (self.sess / "1_c3dfiles" / "SJ1.c3d").write_bytes(b"c3d")
        self.assertTrue(any("not listed under trials" in p
                            for p in self.form().problems()))

    def test_duplicate_emg_map_key_is_caught(self):
        """safe_load cannot see this: YAML keeps the last and says nothing."""
        dup = SESSION_YAML.replace(
            "  Voltage_2-VL:\n  - vaslat_l\n",
            "  Voltage_2-VL:\n  - vaslat_l\n  Voltage_1-VM:\n  - WRONG_l\n")
        self.yaml_path.write_text(dup, encoding="utf-8")
        f = self.form()
        self.assertEqual(f.duplicate_emg_keys(), ["Voltage_1-VM"])
        self.assertTrue(any("DUPLICATE emg_map" in p for p in f.problems()))


class TestSurgicalEditing(_Session):
    """Every test here asserts what did NOT change, as well as what did."""

    def saved(self, edit):
        f = self.form()
        edit(f)
        f.save(backup=False)
        return self.yaml_path.read_text(encoding="utf-8")

    def test_comments_survive_a_scalar_edit(self):
        out = self.saved(lambda f: f.set_scalar("body_mass", 75.2))
        self.assertIn("ONE CEINMS CALIBRATION PER FATIGUE STATE", out)
        self.assertIn("# weighed from the static trial", out)
        self.assertIn("body_mass: 75.2", out)
        self.assertNotIn("89.4", out)

    def test_only_the_edited_line_changes(self):
        before = SESSION_YAML.splitlines()
        after = self.saved(lambda f: f.set_scalar("static_trial", "HAB1")).splitlines()
        self.assertEqual(len(before), len(after))
        differing = [i for i, (a, b) in enumerate(zip(before, after)) if a != b]
        self.assertEqual(len(differing), 1, "more than one line moved")
        self.assertIn("static_trial", after[differing[0]])

    def test_block_list_stays_block(self):
        out = self.saved(lambda f: f.set_list(
            "calibration_trials", ["Run_baselineA1", "Run_baselineA2", "HAB1"]))
        self.assertIn("calibration_trials:\n- Run_baselineA1\n- Run_baselineA2\n- HAB1\n", out)
        self.assertIn("normalisation_trials:\n- HAB1\n- HAB2\n", out)

    def test_shrinking_a_list(self):
        out = self.saved(lambda f: f.set_list("normalisation_trials", ["HAB2"]))
        self.assertIn("normalisation_trials:\n- HAB2\n", out)
        self.assertIn("emg_map:", out)               # the next key survived

    def test_emptying_a_list(self):
        out = self.saved(lambda f: f.set_list("calibration_trials", []))
        self.assertIn("calibration_trials: []", out)

    def test_trial_type_change_touches_one_trial(self):
        out = self.saved(lambda f: f.set_trial_type("HAB2", "calibration"))
        self.assertIn("  HAB2:\n    type: calibration\n", out)
        self.assertIn("  HAB1:\n    type: generic\n", out)
        self.assertIn("  static1:\n    type: static\n", out)

    def test_new_trial_is_added(self):
        out = self.saved(lambda f: f.set_trial_type("SJ1", "jump"))
        self.assertIn("SJ1", out)
        self.assertIn("type: jump", out)
        import yaml
        self.assertEqual(yaml.safe_load(out)["trials"]["SJ1"]["type"], "jump")

    def test_ceinms_scalars(self):
        out = self.saved(lambda f: f.set_ceinms(alpha=5, gamma=2000))
        import yaml
        c = yaml.safe_load(out)["ceinms"]
        self.assertEqual((c["alpha"], c["beta"], c["gamma"]), (5, 1, 2000))

    def test_iterations_block_is_never_touched(self):
        out = self.saved(lambda f: (f.set_scalar("subject", 22),
                                    f.set_list("normalisation_trials", ["HAB1"]),
                                    f.set_trial_type("HAB1", "calibration")))
        self.assertIn("  rajagopal_fai:\n    generic: Rajagopal2015_FAI_os4.osim\n", out)
        self.assertIn("    label: Rajagopal FAI 022", out)

    def test_result_still_parses_and_keeps_every_key(self):
        import yaml
        before = yaml.safe_load(SESSION_YAML)
        out = self.saved(lambda f: (f.set_scalar("body_mass", 70.0),
                                    f.set_list("calibration_trials", ["HAB1"]),
                                    f.set_trial_type("HAB2", "calibration")))
        after = yaml.safe_load(out)
        self.assertEqual(set(before), set(after))
        self.assertEqual(before["emg_map"], after["emg_map"])
        self.assertEqual(before["iterations"], after["iterations"])

    def test_no_edits_means_no_write_needed(self):
        f = self.form()
        self.assertFalse(f.dirty())

    def test_save_makes_a_backup_by_default(self):
        f = self.form()
        f.set_scalar("body_mass", 60.0)
        f.save()
        siblings = list(self.sess.glob("session.yaml*"))
        self.assertGreater(len(siblings), 1, f"no backup written: {siblings}")


if __name__ == "__main__":
    unittest.main(verbosity=2)


class TestIterations(_Session):
    """Add / duplicate / remove iterations, and edit their fields."""

    def saved(self, edit):
        f = self.form()
        edit(f)
        f.save(backup=False)
        return self.yaml_path.read_text(encoding="utf-8")

    def test_reads_the_existing_block(self):
        its = self.form().iterations()
        self.assertEqual(list(its), ["rajagopal_fai"])
        self.assertEqual(its["rajagopal_fai"]["so_model"], "022_Rajagopal2015_FAI.osim")

    def test_add_a_second_arm(self):
        import yaml
        out = self.saved(lambda f: f.add_iteration(
            "mri_torsion", generic="Rajagopal2015_FAI_os4.osim",
            so_model="022_mri.osim", ceinms_model="022_mri.osim",
            prescaled=True, linear_scaling=False, label="022 MRI torsion"))
        blocks = yaml.safe_load(out)["iterations"]
        self.assertEqual(set(blocks), {"rajagopal_fai", "mri_torsion"})
        new = blocks["mri_torsion"]
        self.assertEqual(new["so_model"], "022_mri.osim")
        self.assertIs(new["prescaled"], True)
        self.assertIs(new["linear_scaling"], False)
        # and the original arm is untouched, comments included
        self.assertIn("ONE CEINMS CALIBRATION PER FATIGUE STATE", out)
        self.assertEqual(blocks["rajagopal_fai"]["label"], "Rajagopal FAI 022")

    def test_adding_a_duplicate_name_is_refused(self):
        f = self.form()
        with self.assertRaises(ValueError):
            f.add_iteration("rajagopal_fai")

    def test_duplicate_then_edit_is_the_two_arm_workflow(self):
        import yaml
        def edit(f):
            f.duplicate_iteration("rajagopal_fai", "mri_torsion")
            f.set_iteration_field("mri_torsion", "so_model", "022_mri.osim")
            f.set_iteration_field("mri_torsion", "label", "022 MRI torsion")
        blocks = yaml.safe_load(self.saved(edit))["iterations"]
        self.assertEqual(blocks["mri_torsion"]["so_model"], "022_mri.osim")
        self.assertEqual(blocks["rajagopal_fai"]["so_model"],
                         "022_Rajagopal2015_FAI.osim")

    def test_boolean_fields_stay_yaml_booleans(self):
        import yaml
        out = self.saved(lambda f: f.set_iteration_field(
            "rajagopal_fai", "prescaled", False))
        self.assertIs(yaml.safe_load(out)["iterations"]["rajagopal_fai"]["prescaled"],
                      False)

    def test_delete_an_iteration(self):
        import yaml
        f = self.form()
        f.add_iteration("scratch", so_model="x.osim")
        f.save(backup=False)
        f = self.form()
        f.delete_iteration("scratch")
        f.save(backup=False)
        out = yaml.safe_load(self.yaml_path.read_text(encoding="utf-8"))
        self.assertEqual(list(out["iterations"]), ["rajagopal_fai"])


class TestEmgFilter(_Session):
    def saved(self, edit):
        f = self.form()
        edit(f)
        f.save(backup=False)
        return self.yaml_path.read_text(encoding="utf-8")

    def test_effective_settings_default_when_absent(self):
        s = self.form().emg_filter()
        self.assertEqual(s["bandpass_high"], 95.0)
        self.assertEqual(s["envelope_lowpass"], 6.0)

    def test_writing_only_what_differs(self):
        import yaml
        out = self.saved(lambda f: f.set_emg_filter(
            bandpass_low=20.0, bandpass_high=350.0, envelope_lowpass=6.0))
        block = yaml.safe_load(out)["emg_filter"]
        self.assertEqual(block, {"bandpass_high": 350.0},
                         "values equal to the default should not be written")

    def test_all_defaults_writes_nothing(self):
        import yaml
        out = self.saved(lambda f: f.set_emg_filter(bandpass_low=20.0,
                                                    envelope_lowpass=6.0))
        self.assertNotIn("emg_filter", yaml.safe_load(out))

    def test_the_written_block_is_read_back_by_emg_filter(self):
        from bioscout.utils.emg_filter import settings_for
        import yaml
        out = self.saved(lambda f: f.set_emg_filter(bandpass_high=350.0,
                                                    envelope_order=2))
        s = settings_for(yaml.safe_load(out))
        self.assertEqual(s["bandpass_high"], 350.0)
        self.assertEqual(s["envelope_order"], 2)
        self.assertEqual(s["bandpass_low"], 20.0)


class TestTrialFields(_Session):
    """`time_range` and friends — the per-trial keys beyond `type`."""

    def saved(self, edit):
        f = self.form()
        edit(f)
        f.save(backup=False)
        return self.yaml_path.read_text(encoding="utf-8")

    def test_time_range_is_written_in_flow_style(self):
        import yaml
        out = self.saved(lambda f: f.set_trial_field(
            "Run_baselineA1", "time_range", [3.415, 4.85]))
        self.assertIn("time_range: [3.415, 4.85]", out)
        self.assertEqual(yaml.safe_load(out)["trials"]["Run_baselineA1"]["time_range"],
                         [3.415, 4.85])

    def test_type_survives_a_time_range_write(self):
        import yaml
        out = self.saved(lambda f: f.set_trial_field(
            "Run_baselineA1", "time_range", [1.0, 2.0]))
        self.assertEqual(yaml.safe_load(out)["trials"]["Run_baselineA1"]["type"],
                         "running")

    def test_updating_an_existing_time_range(self):
        import yaml
        f = self.form()
        f.set_trial_field("HAB1", "time_range", [0.0, 1.0])
        f.save(backup=False)
        f = self.form()
        f.set_trial_field("HAB1", "time_range", [0.5, 1.5])
        f.save(backup=False)
        out = yaml.safe_load(self.yaml_path.read_text(encoding="utf-8"))
        self.assertEqual(out["trials"]["HAB1"]["time_range"], [0.5, 1.5])

    def test_set_trial_type_still_works(self):
        out = self.saved(lambda f: f.set_trial_type("HAB2", "calibration"))
        self.assertIn("  HAB2:\n    type: calibration\n", out)
